name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.1
      with:
        python-versions: 'cp35-cp35m cp36-cp36m cp37-cp37m cp38-cp38'
